config/routes.rb
Rails.application.routes.draw do
  get "spells", to: "spells#index"
  get "spells/:id", to: "spells#show", as: "spell"
  resources :characters
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "characters#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/character.rb
class Character < ApplicationRecord
  has_one :stat_set, dependent: :destroy
  has_one :skill_set, dependent: :destroy
  has_one :trait_set, dependent: :destroy

  accepts_nested_attributes_for :stat_set
  accepts_nested_attributes_for :skill_set
  accepts_nested_attributes_for :trait_set

  has_many :character_spells
  has_many :spells, through: :character_spells

  before_create :ensure_defaults

  def ensure_defaults
    build_default_stat_set if not stat_set
    build_default_skill_set if not skill_set
    build_default_trait_set if not trait_set
  end

  private
    def build_default_stat_set
      build_stat_set  strength: 0,
                      dexterity: 0,
                      intelligence: 0,
                      will: 0
    end

    def build_default_skill_set
      build_skill_set arcana: 0,
                      insight: 0,
                      examination: 0,
                      finesse: 0,
                      might: 0,
                      lore: 0,
                      influence: 0,
                      naturecraft: 0,
                      stealth: 0,
                      perception: 0
    end

    def build_default_trait_set
      build_trait_set initiative:        0,
                      speed:             30,
                      hit_die:           "1d6",
                      current_hit_dice:  1,
                      max_hit_dice:      1,
                      current_actions:   3,
                      max_actions:       3,
                      armor:             0,
                      temp_hp:           0,
                      current_hp:        10,
                      max_hp:            10,
                      current_wounds:    6,
                      max_wounds:        6
    end
end

app/models/character_spell.rb
class CharacterSpell < ApplicationRecord
  belongs_to :character
  belongs_to :spell
end

app/models/skill_set.rb
class SkillSet < ApplicationRecord
  belongs_to :character
end

app/models/spell.rb
class Spell < ApplicationRecord
end

app/models/stat_set.rb
class StatSet < ApplicationRecord
  belongs_to :character
end

app/models/trait_set.rb
class TraitSet < ApplicationRecord
  belongs_to :character
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_action :set_character, only: %i[ show edit update destroy ]

  # GET /characters or /characters.json
  def index
    @characters = Character.all
  end

  # GET /characters/1 or /characters/1.json
  def show
  end

  # GET /characters/new
  def new
    @character = Character.new
    @character.ensure_defaults
  end

  # GET /characters/1/edit
  def edit
  end

  # POST /characters or /characters.json
  def create
    @character = Character.new(character_params)

    respond_to do |format|
      if @character.save
        format.html { redirect_to @character, notice: "Character was successfully created." }
        format.json { render :show, status: :created, location: @character }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /characters/1 or /characters/1.json
  def update
    respond_to do |format|
      if @character.update(character_params)
        format.html { redirect_to @character, notice: "Character was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @character }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /characters/1 or /characters/1.json
  def destroy
    @character.destroy!

    respond_to do |format|
      format.html { redirect_to characters_path, notice: "Character was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_character
      @character = Character.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through using expect.
    def character_params
      stat_set_params_list = [ :id, :strength, :dexterity, :intelligence, :will ]
      skill_set_params_list = [ :id, :character, :arcana, :insight, :examination, :finesse, :might, :lore, :influence, :naturecraft, :stealth, :perception ]
      trait_set_params_list = [ :id, :initiative, :speed, :hit_die, :current_hit_dice, :max_hit_dice, :current_actions, :max_actions, :armor, :temp_hp, :current_hp, :max_hp, :current_wounds, :max_wounds ]
      params.expect(character: [
        :name,
        :race,
        :nimble_class,
        :level,
        :background,
        :description,
        :languages,
        {
          trait_set_attributes: trait_set_params_list,
          stat_set_attributes: stat_set_params_list,
          skill_set_attributes: skill_set_params_list
        },
        spell_ids: []
      ])
    end
end

app/controllers/spells_controller.rb
class SpellsController < ApplicationController
  before_action :set_spell, only: %i[ show ]
  def index
    @spells = Spell.all
  end

  def show
  end

  private
    def set_spell
      @spell = Spell.find(params.expect(:id))
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/spells_helper.rb
module SpellsHelper
  def name_of_tier(tier)
    case tier
    when 0
      "Cantrip"
    when -1
      "Utility"
    else
      "Tier " + tier.to_s
    end
  end

  def name_of_action_cost(action_cost)
    action_cost.to_s
  end

  def name_of_target(target)
    case target
    when 0
      "Self"
    when 99
      "AoE"
    else
      "#{target} #{pluralize(target, 'target')}"
    end
  end

  def name_of_range(range)
    range.to_s
  end

  def name_of_casting_time(casting_time)
    case casting_time
    when 0
      "Instant"
    else
      casting_time.to_s + " minutes"
    end
  end

  def color_from_spell_school(spell_school)
    school_to_spell = {
      "Fire" =>       "text-red-700",
      "Ice" =>        "text-blue-300",
      "Lightning" =>  "text-indigo-700",
      "Wind" =>       "text-green-700",
      "Radiant" =>    "text-yellow-600",
      "Necrotic" =>   "text-purple-700"
    }

    school_to_spell.fetch(spell_school.capitalize, "text-black")
  end
end

app/views/attributes/_stats_and_skills.html.erb
<div class="flex gap-20 items-center">
  <%= form.fields_for :stat_set do |stat_set_fields| %>
    <div class="flex flex-col justify-center items-center">
      <%= stat_set_fields.text_field :strength, disabled: read_only, placeholder: 0, class: "border-b-1 max-w-10 text-center text-4xl" %>
      <%= stat_set_fields.label :strength, "STR", class: "text-xs text-gray-500" %>
    </div>
    <div class="flex flex-col justify-center items-center">
      <%= stat_set_fields.text_field :dexterity, disabled: read_only, placeholder: 0, class: "border-b-1 max-w-10 text-center text-4xl" %>
      <%= stat_set_fields.label :dexterity, "DEX", class: "text-xs text-gray-500" %>
    </div>
    <div class="flex flex-col justify-center items-center">
      <%= stat_set_fields.text_field :intelligence, disabled: read_only, placeholder: 0, class: "border-b-1 max-w-10 text-center text-4xl" %>
      <%= stat_set_fields.label :intelligence, "INT", class: "text-xs text-gray-500" %>
    </div>
    <div class="flex flex-col justify-center items-center">
      <%= stat_set_fields.text_field :will, disabled: read_only, placeholder: 0, class: "border-b-1 max-w-10 text-center text-4xl" %>
      <%= stat_set_fields.label :will, "WIL", class: "text-xs text-gray-500" %>
    </div>
  <% end %>
</div>
<div class="flex gap-10">
  <%= form.fields_for :skill_set do |skill_set_fields| %>
    <div class="flex flex-col justify-center items-center">
      <%= skill_set_fields.text_field :arcana, disabled: read_only, placeholder: 0, class: "border-b-1 max-w-10 text-center text-4xl" %>
      <%= skill_set_fields.label :arcana, "Arcana", class: "text-xs text-gray-500" %>
    </div>
    <div class="flex flex-col justify-center items-center">
      <%= skill_set_fields.text_field :insight, disabled: read_only, placeholder: 0, class: "border-b-1 max-w-10 text-center text-4xl" %>
      <%= skill_set_fields.label :insight, "Insight", class: "text-xs text-gray-500" %>
    </div>
    <div class="flex flex-col justify-center items-center">
      <%= skill_set_fields.text_field :examination, disabled: read_only, placeholder: 0, class: "border-b-1 max-w-10 text-center text-4xl" %>
      <%= skill_set_fields.label :examination, "Examination", class: "text-xs text-gray-500" %>
    </div>
    <div class="flex flex-col justify-center items-center">
      <%= skill_set_fields.text_field :finesse, disabled: read_only, placeholder: 0, class: "border-b-1 max-w-10 text-center text-4xl" %>
      <%= skill_set_fields.label :finesse, "Finesse", class: "text-xs text-gray-500" %>
    </div>
    <div class="flex flex-col justify-center items-center">
      <%= skill_set_fields.text_field :might, disabled: read_only, placeholder: 0, class: "border-b-1 max-w-10 text-center text-4xl" %>
      <%= skill_set_fields.label :might, "Might", class: "text-xs text-gray-500" %>
    </div>
    <div class="flex flex-col justify-center items-center">
      <%= skill_set_fields.text_field :lore, disabled: read_only, placeholder: 0, class: "border-b-1 max-w-10 text-center text-4xl" %>
      <%= skill_set_fields.label :lore, "Lore", class: "text-xs text-gray-500" %>
    </div>
    <div class="flex flex-col justify-center items-center">
      <%= skill_set_fields.text_field :influence, disabled: read_only, placeholder: 0, class: "border-b-1 max-w-10 text-center text-4xl" %>
      <%= skill_set_fields.label :influence, "Influence", class: "text-xs text-gray-500" %>
    </div>
    <div class="flex flex-col justify-center items-center">
      <%= skill_set_fields.text_field :naturecraft, disabled: read_only, placeholder: 0, class: "border-b-1 max-w-10 text-center text-4xl" %>
      <%= skill_set_fields.label :naturecraft, "Naturecraft", class: "text-xs text-gray-500" %>
    </div>
    <div class="flex flex-col justify-center items-center">
      <%= skill_set_fields.text_field :stealth, disabled: read_only, placeholder: 0, class: "border-b-1 max-w-10 text-center text-4xl" %>
      <%= skill_set_fields.label :stealth, "Stealth", class: "text-xs text-gray-500" %>
    </div>
    <div class="flex flex-col justify-center items-center">
      <%= skill_set_fields.text_field :perception, disabled: read_only, placeholder: 0, class: "border-b-1 max-w-10 text-center text-4xl" %>
      <%= skill_set_fields.label :perception, "Perception", class: "text-xs text-gray-500" %>
    </div>
  <% end %>
</div>

app/views/attributes/_subform.html.erb
<div class="flex gap-20 items-center">
  <%= form.fields_for :stats do |stat_fields| %>
    <div class="flex flex-col justify-center items-center">
      <%= stat_fields.text_field :value, placeholder: 0, class: "border-b-1 max-w-10 text-center text-4xl" %>
      <label class="text-xs text-gray-500">
        <%= shorthand(stat_fields.object.name) %>
        <%= stat_fields.hidden_field :name %>
      </label>
    </div>
  <% end %>
</div>
  <div class="flex gap-10">
    <%= form.fields_for :skills do |skill_fields| %>
      <div class="flex flex-col justify-center items-center">
        <%= skill_fields.text_field :value, placeholder: 0, class: "border-b-1 max-w-10 text-center text-4xl" %>
        <label class="text-xs text-gray-500">
          <%= skill_fields.object.name %>
          <%= skill_fields.hidden_field :name%>
        </label>
      </div>
    <% end %>
  </div>

app/views/attributes/_trait.html.erb
<div class="flex flex-col justify-center items-center">
  <%= field %>
  <label class="text-xs text-gray-500"><%= label %></label>
</div>

app/views/attributes/_trait_set.html.erb
<%= form.fields_for :trait_set do |trait_set_fields| %>
  <div id="action-traits" class="flex gap-1">
    <%= render partial: "attributes/trait", locals: { field: trait_set_fields.number_field(:initiative, disabled: read_only, placeholder: 0, class: "border-b-1 max-w-20 text-center text-4xl"), label: "Initiative"} %>
    <%= render partial: "attributes/trait", locals: { field: trait_set_fields.number_field(:speed, disabled: read_only, placeholder: 0, class: "border-b-1 max-w-20 text-center text-4xl"), label: "Speed"} %>
    <%= render partial: "attributes/trait", locals: { field: trait_set_fields.number_field(:current_actions, disabled: read_only, placeholder: 0, class: "border-b-1 max-w-20 text-center text-4xl"), label: "Current Actions"} %>
    <%= render partial: "attributes/trait", locals: { field: trait_set_fields.number_field(:max_actions, disabled: read_only, placeholder: 0, class: "border-b-1 max-w-20 text-center text-4xl"), label: "Max Actions"} %>
  </div>
  <div id="hit-die-traits" class="flex gap-1">
    <%= render partial: "attributes/trait", locals: { field: trait_set_fields.text_field(:hit_die, disabled: read_only, placeholder: "1d6", class: "border-b-1 max-w-20 text-center text-4xl"), label: "Hit Die"} %>
    <%= render partial: "attributes/trait", locals: { field: trait_set_fields.number_field(:current_hit_dice, disabled: read_only, placeholder: 0, class: "border-b-1 max-w-20 text-center text-4xl"), label: "Current Hit Dice"} %>
    <%= render partial: "attributes/trait", locals: { field: trait_set_fields.number_field(:max_hit_dice, disabled: read_only, placeholder: 0, class: "border-b-1 max-w-20 text-center text-4xl"), label: "Max Hit Dice"} %>
  </div>
  <div id="health-traits" class="flex gap-1">
    <%= render partial: "attributes/trait", locals: { field: trait_set_fields.number_field(:armor, disabled: read_only, placeholder: 0, class: "border-b-1 max-w-20 text-center text-4xl"), label: "Armor"} %>
    <%= render partial: "attributes/trait", locals: { field: trait_set_fields.number_field(:temp_hp, disabled: read_only, placeholder: 0, class: "border-b-1 max-w-20 text-center text-4xl"), label: "Temp HP"} %>
    <%= render partial: "attributes/trait", locals: { field: trait_set_fields.number_field(:current_hp, disabled: read_only, placeholder: 0, class: "border-b-1 max-w-20 text-center text-4xl"), label: "Current HP"} %>
    <%= render partial: "attributes/trait", locals: { field: trait_set_fields.number_field(:max_hp, disabled: read_only, placeholder: 0, class: "border-b-1 max-w-20 text-center text-4xl"), label: "Max HP"} %>
    <%= render partial: "attributes/trait", locals: { field: trait_set_fields.number_field(:current_wounds, disabled: read_only, placeholder: 0, class: "border-b-1 max-w-20 text-center text-4xl"), label: "Current Wounds"} %>
    <%= render partial: "attributes/trait", locals: { field: trait_set_fields.number_field(:max_wounds, disabled: read_only, placeholder: 0, class: "border-b-1 max-w-20 text-center text-4xl"), label: "Max Wounds"} %>
  </div>
<% end %>

app/views/characters/_form.html.erb
<%= form_with(model: character, class: "contents") do |form| %>
  <% if character.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(character.errors.count, "error") %> prohibited this character from being saved:</h2>

      <ul class="list-disc ml-6">
        <% character.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="flex flex-col gap-2 my-5 max-w-235">
    <div id="character-summary" class="flex gap-5 border-1 p-2">
      <div class="min-w-50">
          <%= form.text_field :name, disabled: read_only, placeholder: "Enter Name", class: ["w-full border-b-1", {"border-gray-400 focus:outline-blue-600": character.errors[:name].none?, "border-red-400 focus:outline-red-600": character.errors[:name].any?}] %>
        <p class="text-gray-500 text-xs">Name</p>
      </div>
      <div class="min-w-50">
          <%= form.text_field :race, disabled: read_only, placeholder: "Enter Race", class: ["w-full border-b-1", {"border-gray-400 focus:outline-blue-600": character.errors[:race].none?, "border-red-400 focus:outline-red-600": character.errors[:race].any?}] %>
        <p class="text-gray-500 text-xs">Race</p>
      </div>
      <div class="min-w-25">
          <%= form.text_field :nimble_class, disabled: read_only, placeholder: "Enter Class", class: ["w-full border-b-1", {"border-gray-400 focus:outline-blue-600": character.errors[:nimble_class].none?, "border-red-400 focus:outline-red-600": character.errors[:nimble_class].any?}] %>
        <p class="text-gray-500 text-xs">Class</p>
      </div>
      <div class="min-w-10">
        <%= form.number_field :level, disabled: read_only, placeholder: "Enter Level", class: ["w-full border-b-1", {"border-gray-400 focus:outline-blue-600": character.errors[:level].none?, "border-red-400 focus:outline-red-600": character.errors[:level].any?}] %>
        <p class="text-gray-500 text-xs">Level</p>
      </div>
      <div class="min-w-75">
          <%= form.text_field :background, disabled: read_only, placeholder: "Enter Background", class: ["w-full border-b-1", {"border-gray-400 focus:outline-blue-600": character.errors[:background].none?, "border-red-400 focus:outline-red-600": character.errors[:background].any?}] %>
        <p class="text-gray-500 text-xs">Background</p>
      </div>
    </div>
    <div id="character-info" class="border-1 p-2">
      <div class="">
        <%= form.textarea :description, disabled: read_only, rows: 4, placeholder: "Enter Description", class: ["w-full border-b-1", {"border-gray-400 focus:outline-blue-600": character.errors[:description].none?, "border-red-400 focus:outline-red-600": character.errors[:description].any?}] %>
        <p class="text-gray-500 text-xs">Description</p>
      </div>
      <div class="">
        <%= form.text_field :languages, disabled: read_only, placeholder: "Enter Languages", class: [" w-full border-b-1", {"border-gray-400 focus:outline-blue-600": character.errors[:languages].none?, "border-red-400 focus:outline-red-600": character.errors[:languages].any?}] %>
        <p class="text-gray-500 text-xs">Languages</p>
      </div>
    </div>
    <div id="character-stats-and-skills" class="flex flex-col justify-center items-center gap-5 border-1 p-2"">
      <%= render partial: 'attributes/stats_and_skills', locals: { form: form, read_only: read_only } %>
    </div>
    <div id="character-trait-set" class="flex flex-wrap justify-center items-center gap-5 border-1 p-2">
        <%= render partial: 'attributes/trait_set', locals: {form: form, read_only: read_only} %>
    </div>

    <div id="character-spells" class="border-1 p-2">
      <% if not read_only %>
        <%= form.collection_check_boxes :spell_ids, Spell.order(:tier), :id, :name do |cb| %>
          <label class="inline-flex items-center gap-2 py-1">
            <%= cb.check_box class: "rounded" %>
            <span class="<%= color_from_spell_school(cb.object.school)%>"><%=cb.object.name %></span>
          </label>
        <% end %>
      <% else %>
       <% character.spells.each do |spell| %> 
        <span class="<%= color_from_spell_school(spell.school)%>"><%=spell.name %></span>
       <% end %>
      <% end %>
    </div>
  </div>

  <% unless read_only %>
    <div class="inline">
      <%= form.submit class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
    </div>
  <% end %>
<% end %>

app/views/characters/edit.html.erb
<% content_for :title, "Editing character" %>

<div class="">
  <h1 class="font-bold text-4xl">Editing character</h1>

  <%= render "form", character: @character, read_only: false %>

  <%= link_to "Show this character", @character, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to characters", characters_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/characters/index.html.erb
<% content_for :title, "Characters" %>

<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Characters</h1>
    <%= link_to "New character", new_character_path, class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white block font-medium" %>
  </div>

  <div id="characters" class="min-w-full divide-y divide-gray-200 space-y-5">
    <% if @characters.any? %>
      <% @characters.each do |character| %>
        <div class="flex flex-col sm:flex-row justify-between items-center pb-5 sm:pb-0">
          <%= render "form", character: character, read_only: true %>
          <div class="w-full sm:w-auto flex flex-col sm:flex-row space-x-2 space-y-2">
            <%= link_to "Show", character, class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
            <%= link_to "Edit", edit_character_path(character), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
            <%= button_to "Destroy", character, method: :delete, class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
          </div>
        </div>
      <% end %>
    <% else %>
      <p class="text-center my-10">No characters found.</p>
    <% end %>
  </div>
</div>

app/views/characters/new.html.erb
<% content_for :title, "New character" %>

<div class="">
  <h1 class="font-bold text-4xl">New character</h1>

  <%= render "form", character: @character, read_only: false %>

  <%= link_to "Back to characters", characters_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/characters/show.html.erb
<% content_for :title, "Showing character" %>

<div class="md:w-2/3 w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <h1 class="font-bold text-4xl">Showing character</h1>

  <%= render "form", character: @character, read_only: true %>

  <%= link_to "Edit this character", edit_character_path(@character), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to characters", characters_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= button_to "Destroy this character", @character, method: :delete, form_class: "sm:inline-block mt-2 sm:mt-0 sm:ml-2", class: "w-full rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Simple Nimble" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container font-macondo mx-auto mt-28 px-5 flex flex-col items-center ">
      <%= yield %>
    </main>
  </body>
</html>

app/views/spells/_spell.html.erb
<div id="<%= dom_id spell %>" class="flex flex-col items-center w-100 gap-1 border-1 p-2">
  
  <div class="flex self-stretch justify-between">
    <p class="text-3xl self-start border-1 <%= color_from_spell_school spell.school %>"><%= spell.name %>  </p>
    <p><%= name_of_tier spell.tier %></p>
  </div>
  <div class="flex flex-wrap gap-5 items-between ">
    
    <p>Action Cost: <%= name_of_action_cost spell.action_cost %></p>
    <p>Range: <%= name_of_range spell.range %></p>
    <p>Damage: <%= spell.damage %></p>
    <p><%= name_of_casting_time spell.casting_time %></p>
  </div>
  <p><%= spell.description %></p>
  <p><%= spell.high_level %></p>
  <p><%= spell.upcast %></p>


</div>

app/views/spells/index.html.erb
<div>
  <h1 class="font-bold text-4xl">Spells#index</h1>
  <p>Find me in app/views/spells/index.html.erb</p>

  <div id="spells" class="min-w-full divide-y divide-gray-200 space-y-5">
    <% if @spells.any? %>
      <% @spells.each do |spell| %>
        <div class="flex flex-col justify-between items-center pb-5">
          <%= render spell %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/spells/show.html.erb
<div>
  <h1 class="font-bold text-4xl">Spells#show</h1>
  <p>Find me in app/views/spells/show.html.erb</p>
  <%= render @spell %>
</div>